"""Aggregate per-video engagement stats from the silver music table.

Groups by author and video title at minute-level granularity, computing total
views, likes, and comments per snapshot window.
"""


from pyspark.sql import DataFrame
from pyspark.sql.functions import col, date_trunc, sum, row_number
from pyspark.sql import Window


# Update 20.08.2025: the previous aggregation logic was wrong.

# Say we have a video with two records:
# _ingested_at view_count
# 15:20:05 500
# 15:20:10: 600
# After truncating the seconds, we'll have two identical records (_ingested_at-identicial to be precise) with 15:20:00
# The sum function will wrongly says: 15:20:00 1100. 
# To get correct metric values, we'll need to extract the LAST metric value (ordered by _ingested_at).
# Note it's not enough to take maximum values grouped by video and ingested_date: (here comes the Domain knowledge:)
# Commomn sense says these metrics can only grow (or at worst remain constant) with time, but that's not true
# YouTube can remove "fake" views, e.g. those generated by bots, so on a graph you could see a sharp decline (e.g. -1mln views).



def aggregate_video_stats(silver_df: DataFrame,
timestamp_granularity: str = "minute") -> DataFrame:
    """Aggregate total engagement metrics per video per ingestion-timestamp_granularity.

    Truncates the ``_ingested_at`` timestamp to pre-defined precision and groups
    the silver table by author, video title, and truncated timestamp.

    Args:
        silver_df: Silver-layer DataFrame containing columns
            ``video_title``, ``view_count``, ``like_count``, ``comment_count``,
            and ``_ingested_at``.
        timestamp_granularity: Granularity of timestamp to aggregate to (e.g. "minute", "hour", "day", etc)

    Returns:
        DataFrame with columns ``video_title``,
        ``ingested_at_{granularity}``, ``total_views``, ``total_likes``, and
        ``total_comments`` only.
    """
    assert timestamp_granularity in ["minute", "hour", "day", "week", "month"], f"Invalid timestamp granularity: {timestamp_granularity} (or valid but let's be reasonable - we don't need such low granularity)"

    ingestion_col = f"ingested_at_{timestamp_granularity}s"

    silver_df_time = silver_df.withColumns({
        ingestion_col: date_trunc(timestamp_granularity, col("_ingested_at")),
    })

    window_spec = Window.partitionBy("video_id").orderBy(col(ingestion_col).desc())

    silver_df_time = (silver_df_time.withColumn("row_number", row_number().over(window_spec))
                        .filter(col("row_number")==1).drop("row_number"))


    cols_to_rename = {
        "view_count": "total_views",
        "like_count": "total_likes",
        "comment_count":"total_comments"
    }

    silver_df_time = silver_df_time.withColumnsRenamed(cols_to_rename)
 

    return silver_df_time.select(
        "video_id",
        ingestion_col,
        "total_views",
        "total_likes",
        "total_comments",
    )